### PR TITLE
Properly (hackishly) handle commits without parents

### LINKED ISSUE #13: Action fails when there is no parent commit (i.e. on initial commit)
```
❯ git log
commit 2a0686315f70b0e84e1cc097a23ac5934238ff67 (HEAD -> main, origin/main)
Date:   Fri Dec 8 13:26:30 2023 +0100

    Initial commit
```

```
no base commit found, assuming this is a new branch, fetching parent commit of 2a0686315f70b0e84e1cc097a23ac5934238ff67 from api
Error: could not retrieve parent commit of 2a0686315f[7](https://github.com/<owner>/<project>/actions/runs/7141317909/job/19448373638#step:3:8)0b0e84e1cc097a23ac5934238ff67: Cannot read properties of undefined (reading 'sha')
```

### PR DESCRIPTION
**Pull request by JannikWibkerQC**
Closes #13

### CODE REVIEW

**Comment by JannikWibkerQC** [comment]
Not sure if I don't want to redo this entirely as it is a bit too hacky for my taste. This project was quite clean and easy to reason about before and this changes that quite a bit 😅 

*(Alternatively the issue is closed as won't fix)*

**Comment by jens-ox** [comment]
If this isn't something that is needed during normal use of Git, then I don't see a valid reason to add complexity.

**Comment by JannikWibkerQC** [comment]
Depends on wether creating a repo with this action already configured would count as "during normal use of git". It is quite the rare event that a repo is created and everything configured, but this is also the first interaction you might have with this action :/

I specifically don't want to deal with things like having multiple "initial commits", but dealing with the one that always exists could count as a requirement. Right now I tried to integrate this into the normal flow of the action but I might go ahead and just detect this and exit early with appropriate data (version bump to what is contained in the last commit)

**Review by jens-ox — APPROVED** [review]
Then LGTM! 😄

**Pull request merged**
